### ISSUE TITLE
Max retries exceeded

### ISSUE THREAD

**Issue by bitshiftnetau** [timothymiller/cloudflare-ddns#71]
**Describe the bug**
Retries on subsequent updates post installation are hitting some kind of retry limit, possibly due to "Development mode" enabled on Cloudflare (untested)

**To Reproduce**
1. Install cloudflare-ddns docker on LXC (untested in VM or baremetal install)
2. Run cloudflare-ddns docker
3. wait 5 mins for update OR make adjustments to config file and save

**Expected behavior**
Should update just fine on subsequent requests

**Screenshots**
see log below

**Desktop (please complete the following information):**
 - OS: Docker on ArchLinux LXC in Proxmox

**Additional context**

Upon running the docker up, the ip is updated just fine. Subsequent updates have the following log output to stdout.

```
cloudflare-ddns  | Traceback (most recent call last):
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
cloudflare-ddns  |     conn = connection.create_connection(
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
cloudflare-ddns  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
cloudflare-ddns  |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
cloudflare-ddns  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
cloudflare-ddns  | socket.gaierror: [Errno -3] Try again
cloudflare-ddns  | 
cloudflare-ddns  | During handling of the above exception, another exception occurred:
cloudflare-ddns  | 
cloudflare-ddns  | Traceback (most recent call last):
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
cloudflare-ddns  |     httplib_response = self._make_request(
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
cloudflare-ddns  |     self._validate_conn(conn)
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
cloudflare-ddns  |     conn.connect()
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
cloudflare-ddns  |     conn = self._new_conn()
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
cloudflare-ddns  |     raise NewConnectionError(
cloudflare-ddns  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f29c55f3c10>: Failed to establish a new connection: [Errno -3] Try again
cloudflare-ddns  | 
cloudflare-ddns  | During handling of the above exception, another exception occurred:
cloudflare-ddns  | 
cloudflare-ddns  | Traceback (most recent call last):
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
cloudflare-ddns  |     resp = conn.urlopen(
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
cloudflare-ddns  |     retries = retries.increment(
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 574, in increment
cloudflare-ddns  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
cloudflare-ddns  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.cloudflare.com', port=443): Max retries exceeded with url: /client/v4/zones/<MY ZONE> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f29c55f3c10>: Failed to establish a new connection: [Errno -3] Try again'))
cloudflare-ddns  | 
cloudflare-ddns  | During handling of the above exception, another exception occurred:
cloudflare-ddns  | 
cloudflare-ddns  | Traceback (most recent call last):
cloudflare-ddns  |   File "/cloudflare-ddns.py", line 227, in <module>
cloudflare-ddns  |     updateIPs(getIPs())
cloudflare-ddns  |   File "/cloudflare-ddns.py", line 181, in updateIPs
cloudflare-ddns  |     commitRecord(ip)
cloudflare-ddns  |   File "/cloudflare-ddns.py", line 95, in commitRecord
cloudflare-ddns  |     response = cf_api("zones/" + option['zone_id'], "GET", option)
cloudflare-ddns  |   File "/cloudflare-ddns.py", line 165, in cf_api
cloudflare-ddns  |     response = requests.request(
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 61, in request
cloudflare-ddns  |     return session.request(method=method, url=url, **kwargs)
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
cloudflare-ddns  |     resp = self.send(prep, **send_kwargs)
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
cloudflare-ddns  |     r = adapter.send(request, **kwargs)
cloudflare-ddns  |   File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 516, in send
cloudflare-ddns  |     raise ConnectionError(e, request=request)
cloudflare-ddns  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.cloudflare.com', port=443): Max retries exceeded with url: /client/v4/zones/<MY ZONE> (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f29c55f3c10>: Failed to establish a new connection: [Errno -3] Try again'))
cloudflare-ddns exited with code 1
cloudflare-ddns  | ⚙️ Individually disable IPv4 or IPv6 with new config.json options. Read more about it here: https://github.com/timothymiller/cloudflare-ddns/blob/master/README.md
cloudflare-ddns  | ⚙️ No config detected for 'purgeUnknownRecords' - defaulting to False
cloudflare-ddns  | 🕰️ Updating IPv4 (A) & IPv6 (AAAA) records every 5 minutes
cloudflare-ddns  | 🧩 IPv6 not detected

```

**Comment by bitshiftnetau** [comment]
Have now tested without `Development Mode` enabled in the Cloudflare dashboard and the error persists.

**Comment by Quack6666** [comment]
I'm having the same issue. Seems that sometime it even stop the docker container altogether. Maybe we could add a docker env variable that let us chose the update frequency instead of hardcoding 5 minutes ?

**Comment by typkrft** [comment]
I was running into this error because dns was not resolving and I wasn't using host network mode or a bridge network(?). Oddly enough the vm I was deploying it on was the vm my network uses for dns, but I had to turn off resolved to free up the ports. This may have been resolved simply by setting the host machines DNS. But I decided to add it to the network my pihole container was on and set the dns in the compose file. I'm not saying that everyone's issue, but something worth investigating.

example
```YAML
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare_ddns
    security_opt:
      - no-new-privileges:true
    # network_mode: "host"
    networks:
      pihole:
        ipv4_address: 10.0.4.4
    dns: 10.0.4.3
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker_storage/cloudflare/config.json:/config.json
    restart: always

networks:
  pihole:
    external: true
```

**Comment by timothymiller** [comment]
Network modes other than host are not recommended.
