### ISSUE TITLE
Empty string for subdomains throwing error

### ISSUE THREAD

**Issue by nonsavant** [timothymiller/cloudflare-ddns#73]
**Describe the bug**

Following the documentation, which I now quote:

`"subdomains": "Array of subdomains you want to update the A & where applicable, AAAA records. IMPORTANT! Only write subdomain name. Do not include the base domain name. (e.g. foo or an empty string to update the base domain)",
`

I have defined subdomains in  config.json as follows:

```
      "subdomains": [
        ""
      ],

```

But I am seeing the following errors in the log:

```
🕰️ Updating IPv4 (A) records every 5 minutes
Traceback (most recent call last):
  File "/cloudflare-ddns.py", line 227, in <module>
    updateIPs(getIPs())
  File "/cloudflare-ddns.py", line 181, in updateIPs
    commitRecord(ip)
  File "/cloudflare-ddns.py", line 94, in commitRecord
    subdomains = option["subdomains"]
KeyError: 'subdomains'
```

**To Reproduce**

1. Set up config.json with subdomains defined as above
2. Run the container in docker
3. looks at the logs

**Expected behavior**

I guess, no error?

**Comment by nonsavant** [comment]
Hmph, 

`"subdomains": ""`

seems to work. 

Documentation could be clearer.

**Comment by Szilard95** [comment]
I'm using the same subdomain config you described, it works for me. However, I got the exact same error when the entire `subdomain` key was missing from the config.

**Comment by nonsavant** [comment]
> Hmph,
> 
> `"subdomains": ""`
> 
> seems to work.
> 
> Documentation could be clearer.

Unfortunately, not providing an array means that the record updating code never gets executed (https://github.com/timothymiller/cloudflare-ddns/issues/76).

Switching back to 

```
"subdomains": [
        ""
      ],
```

or 

` "subdomains": [""],`

works, no idea why the original _KeyError: 'subdomains'_ error occurred.

**Comment by Jarsky** [comment]
I'm trying to use this Docker but keep constantly getting this same error


```
⚙️ Individually disable IPv4 or IPv6 with new config.json options. Read more about it here: https://github.com/timothymiller/cloudflare-ddns/blob/master/README.md
⚙️ No config detected for 'purgeUnknownRecords' - defaulting to False
⚙️ No config detected for 'ttl' - defaulting to 300 seconds (5 minutes)
🕰️ Updating IPv4 (A) & IPv6 (AAAA) records every 300 seconds
🧩 IPv6 not detected
Traceback (most recent call last):
  File "/cloudflare-ddns.py", line 261, in <module>
    updateIPs(getIPs())
  File "/cloudflare-ddns.py", line 203, in updateIPs
    commitRecord(ip)
  File "/cloudflare-ddns.py", line 102, in commitRecord
    subdomains = option["subdomains"]
                 ~~~~~~^^^^^^^^^^^^^^
KeyError: 'subdomains'
```

I have tried the array suggestions above and removing it completely but keep getting the error. it's also giving me other config errors which I assume is related to the subdomain key throwing an error?  
  
Here is my json if anyone can shed some light on it? The example on the README is pretty pointless.  
  
```
{
        "cloudflare": [{
                        "authentication": {
                                "api_token": "some_api_token_29EZA",
                                "api_key": {
                                        "api_key": "some_api_key_ce15c5",
                                        "account_email": "myemail@gmail.com"
                                }
                        },
                        "zone_id": "my_first_zone_id_159f",
                        "proxied": false,
                                                "subdomains": [
                                                  {
                                                        "name": "",
                                                        "proxied": false
                                                  },
                                                  {
                                                        "name": "",
                                                        "proxied": false
                                                }
                                        ]
                },
                {
                        "authentication": {
                                "api_token": "some_api_token_29EZA",
                                "api_key": {
                                        "api_key": "some_api_key_ce15c5",
                                        "account_email": "myemail@gmail.com"
                                },
                        "zone_id": "my_second_zone_id_22b6",
                        "proxied": false,
                                                "subdomains": [
                                                  {
                                                        "name": "",
                                                        "proxied": false
                                                  },
                                                  {
                                                        "name": "",
                                                        "proxied": false
                                                }
                                        ]
                        }
                }
        ],
        "a": true,
        "aaaa": false,
        "purgeUnknownRecords": false,
        "ttl": 1200
}
```

Any help appreciated!

**Comment by Jarsky** [comment]
nevermind finally sorted it out, here is multi domain:

```
{
    "cloudflare": [
        {
            "authentication": {
                "api_token": "<api_token>",
                "api_key": {
                    "api_key": "<api_key>",
                    "account_email": "email@address.com"
                }
            },
            "zone_id": "<zone_id_1>",
            "proxied": false,
            "subdomains": []
        },
        {
            "authentication": {
                "api_token": "<api_token>",
                "api_key": {
                    "api_key": "<api_key>",
                    "account_email": "email@address.com"
                }
            },
            "zone_id": "<zone_id_2>",
            "proxied": false,
            "subdomains": []
        }
    ],
    "a": true,
    "aaaa": false,
    "purgeUnknownRecords": false,
    "ttl": 300
}
```
